distInfo=list(
  Gaussian=list(parName=c('mean','sd'),
                parLongName=c('mean','standard deviation'),
                parSymbol=c('mu','sigma'),
                constraints=c('sigma>0'),
                url='https://en.wikipedia.org/wiki/Normal_distribution',
                note=NULL,
                warning=NULL),
  Uniform=list(parName=c('lowBound','highBound'),
               parLongName=c('lower bound','upper bound'),
               parSymbol=c('a','b'),
               constraints=c('a<b'),
               url='https://en.wikipedia.org/wiki/Continuous_uniform_distribution',
               note=NULL,
               warning=NULL),
  Triangle=list(parName=c('peak','lowBound','highBound'),
                parLongName=c('peak','lower bound','upper bound'),
                parSymbol=c('c','a','b'),
                constraints=c('a<c<b'),
                url='https://en.wikipedia.org/wiki/Triangular_distribution',
                note=NULL,
                warning=NULL),
  LogNormal=list(parName=c('meanlog','sdlog'),
                 parLongName=c('mean of log-variable','standard deviation of log-variable'),
                 parSymbol=c('mu','sigma'),
                 constraints=c('sigma>0'),
                 url='https://en.wikipedia.org/wiki/Log-normal_distribution',
                 note=NULL,
                 warning=NULL),
  LogNormal3=list(parName=c('threshold','meanlogexcess','sdlogexcess'),
                  parLongName=c('threshold','mean of log-excesses','standard deviation of log-excesses'),
                  parSymbol=c('gamma','mu','sigma'),
                  constraints=c('sigma>0'),
                  url='https://search.r-project.org/CRAN/refmans/EnvStats/html/Lognormal3.html',
                  note='This is just a shift of the standard log-normal distribution (the latter corresponding to gamma=0)',
                  warning=NULL),
  Exponential=list(parName=c('threshold','scale'),
                   parLongName=c('threshold','scale'),
                   parSymbol=c('mu','sigma'),
                   constraints=c('sigma>0'),
                   url='https://en.wikipedia.org/wiki/Exponential_distribution',
                   note='This is just a shift of the standard exponential distribution (the latter corresponding to mu=0)',
                   warning='The second parameter is the scale and NOT the rate (scale = 1/rate)'),
  GPD=list(parName=c('threshold','scale','shape'),
           parLongName=c('threshold','scale','shape'),
           parSymbol=c('mu','sigma','xi'),
           constraints=c('sigma>0'),
           url='https://en.wikipedia.org/wiki/Generalized_Pareto_distribution',
           note='xi=0 leads to the exponential distribution',
           warning='xi < 0 corresponds to a heavy right tail, xi > 0 to a right-bounded distribution. This is THE OPPOSITE of the parameterization used in e.g. wikipedia or R package evd'),
  Gumbel=list(parName=c('location','scale'),
              parLongName=c('location','scale'),
              parSymbol=c('mu','sigma'),
              constraints=c('sigma>0'),
              url='https://en.wikipedia.org/wiki/Gumbel_distribution',
              note=NULL,
              warning=NULL),
  GEV=list(parName=c('location','scale','shape'),
           parLongName=c('location','scale','shape'),
           parSymbol=c('mu','sigma','xi'),
           constraints=c('sigma>0'),
           url='https://en.wikipedia.org/wiki/Generalized_extreme_value_distribution',
           note='xi=0 leads to the Gumbel distribution',
           warning='xi < 0 corresponds to a heavy right tail, xi > 0 to a right-bounded distribution. This is THE OPPOSITE of the parameterization used in e.g. wikipedia or R package evd'),
  GEV_min=list(parName=c('location','scale','shape'),
               parLongName=c('location','scale','shape'),
               parSymbol=c('mu','sigma','xi'),
               constraints=c('sigma>0'),
               url='https://en.wikipedia.org/wiki/Generalized_extreme_value_distribution#Modification_for_minima_rather_than_maxima',
               note=c('GEV for minima is a distribution family distinct from the standard GEV.',
                      'It is derived from the equality: min(x)=-1*max(-x). Consequently:',
                      'f_{GEV_min}(x;mu,sigma,xi) = f_{GEV}(-x;-mu,sigma,xi)',
                      'F_{GEV_min}(x;mu,sigma,xi) = 1 - F_{GEV}(-x;-mu,sigma,xi)',
                      'Q_{GEV_min}(p;mu,sigma,xi) = -1*Q_{GEV}(1-p;-mu,sigma,xi)',
                      'RANDOM_{GEV_min}(mu,sigma,xi) = -1*RANDOM_{GEV}(-mu,sigma,xi)'),
               warning='see GEV warning for parameterization of the shape parameter xi'),
  Inverse_Chi2=list(parName=c('dof','scale'),
                    parLongName=c('degrees of freedom','scale'),
                    parSymbol=c('nu','sigma'),
                    constraints=c('nu>0','sigma>0'),
                    url='https://en.wikipedia.org/wiki/Scaled_inverse_chi-squared_distribution',
                    note=NULL,
                    warning='this is a SCALED inverse chi-squared distribution'),
  PearsonIII=list(parName=c('location','scale','shape'),
                  parLongName=c('location','scale','shape'),
                  parSymbol=c('mu','sigma','xi'),
                  constraints=c('sigma!=0','xi>0'),
                  url='https://www.rdocumentation.org/packages/PearsonDS/versions/1.2/topics/PearsonIII',
                  note=NULL,
                  warning=NULL),
  Beta=list(parName=c('shape1','shape2'),
            parLongName=c('first shape parameter','second shape parameter'),
            parSymbol=c('alpha','beta'),
            constraints=c('alpha>0','beta>0'),
            url='https://en.wikipedia.org/wiki/Beta_distribution',
            note=NULL,
            warning=NULL),
  Kumaraswamy=list(parName=c('shape1','shape2'),
            parLongName=c('first shape parameter','second shape parameter'),
            parSymbol=c('alpha','beta'),
            constraints=c('alpha>0','beta>0'),
            url='https://en.wikipedia.org/wiki/Kumaraswamy_distribution',
            note=NULL,
            warning=NULL),
  Geometric=list(parName=c('prob'),
                 parLongName=c('success probability'),
                 parSymbol=c('p'),
                 constraints=c('0<p<1'),
                 url='https://en.wikipedia.org/wiki/Geometric_distribution',
                 note=NULL,
                 warning='Version counting the number of trials (rather than failures), i.e. with support starting at 1 (rather than 0). This is different from the version used in R.'),
  Poisson=list(parName=c('rate'),
               parLongName=c('rate'),
               parSymbol=c('lambda'),
               constraints=c('lambda>0'),
               url='https://en.wikipedia.org/wiki/Poisson_distribution',
               note=NULL,
               warning=NULL),
  Bernoulli=list(parName=c('prob'),
                 parLongName=c('success probability'),
                 parSymbol=c('p'),
                 constraints=c('0<p<1'),
                 url='https://en.wikipedia.org/wiki/Bernoulli_distribution',
                 note=NULL,
                 warning=NULL),
  Binomial=list(parName=c('prob','ntrials'),
                parLongName=c('success probability','number of trials'),
                parSymbol=c('p','n'),
                constraints=c('0<p<1','n>0 integer'),
                url='https://en.wikipedia.org/wiki/Binomial_distribution',
                note=NULL,
                warning=NULL),
  NegBinomial=list(parName=c('prob','nfails'),
                   parLongName=c('success probability','number of failures'),
                   parSymbol=c('p','n'),
                   constraints=c('0<p<1','n>0 integer'),
                   url='https://en.wikipedia.org/wiki/Negative_binomial_distribution',
                   note=NULL,
                   warning=NULL),
  FlatPrior=list(parName=c(),
                 parLongName=c(),
                 parSymbol=c(),
                 constraints=c(),
                 url='https://en.wikipedia.org/wiki/Prior_probability#Examples',
                 note='improper distribution corresponding to a uniform distribution on (-infinity;+infinity)',
                 warning='should only be used as a prior distribution'),
  'FlatPrior+'=list(parName=c(),
               parLongName=c(),
               parSymbol=c(),
               constraints=c(),
               url='https://en.wikipedia.org/wiki/Prior_probability#Examples',
               note='improper distribution corresponding to a uniform distribution on [0;+infinity)',
               warning='should only be used as a prior distribution'),
  'FlatPrior-'=list(parName=c(),
                    parLongName=c(),
                    parSymbol=c(),
                    constraints=c(),
                    url='https://en.wikipedia.org/wiki/Prior_probability#Examples',
                    note='improper distribution corresponding to a uniform distribution on (-infinity;0]',
                    warning='should only be used as a prior distribution'),
  FIX=list(parName=c(),
           parLongName=c(),
           parSymbol=c(),
           constraints=c(),
           url=NULL,
           note='Pseudo-distribution used to fix the value of a parameter at its initial guess',
           warning='should only be used as a prior distribution')
)

save(distInfo,file='../data/distInfo.RData')
